
package com.fronya.soap.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PriceServerImpl", targetNamespace = "http://server.soap.fronya.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PriceServerImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrice", targetNamespace = "http://server.soap.fronya.com/", className = "com.fronya.soap.server.GetPrice")
    @ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://server.soap.fronya.com/", className = "com.fronya.soap.server.GetPriceResponse")
    @Action(input = "http://server.soap.fronya.com/PriceServerImpl/getPriceRequest", output = "http://server.soap.fronya.com/PriceServerImpl/getPriceResponse")
    public double getPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePrice", targetNamespace = "http://server.soap.fronya.com/", className = "com.fronya.soap.server.UpdatePrice")
    @ResponseWrapper(localName = "updatePriceResponse", targetNamespace = "http://server.soap.fronya.com/", className = "com.fronya.soap.server.UpdatePriceResponse")
    @Action(input = "http://server.soap.fronya.com/PriceServerImpl/updatePriceRequest", output = "http://server.soap.fronya.com/PriceServerImpl/updatePriceResponse")
    public boolean updatePrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPrice", targetNamespace = "http://server.soap.fronya.com/", className = "com.fronya.soap.server.CreatePrice")
    @ResponseWrapper(localName = "createPriceResponse", targetNamespace = "http://server.soap.fronya.com/", className = "com.fronya.soap.server.CreatePriceResponse")
    @Action(input = "http://server.soap.fronya.com/PriceServerImpl/createPriceRequest", output = "http://server.soap.fronya.com/PriceServerImpl/createPriceResponse")
    public int createPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePrice", targetNamespace = "http://server.soap.fronya.com/", className = "com.fronya.soap.server.DeletePrice")
    @ResponseWrapper(localName = "deletePriceResponse", targetNamespace = "http://server.soap.fronya.com/", className = "com.fronya.soap.server.DeletePriceResponse")
    @Action(input = "http://server.soap.fronya.com/PriceServerImpl/deletePriceRequest", output = "http://server.soap.fronya.com/PriceServerImpl/deletePriceResponse")
    public boolean deletePrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
